description: object_detection_const_hp
data:
  url: https://determined-ai-public-datasets.s3-us-west-2.amazonaws.com/PennFudanPed/PennFudanPed.zip
entrypoint: model_def:ObjectDetectionModel
hyperparameters:
  global_batch_size: 4
  learning_rate: 0.000125
  momentum: 0.75
  weight_decay: 0.0005
min_validation_period:
  epochs: 1
records_per_epoch: 136
searcher:
  max_length:
    epochs: 4
  metric: val_avg_iou
  name: single
  smaller_is_better: false
