deployTarget: "GOOGLE"

proxy:
  enabled: true
  service:
    type: LoadBalancer

cloudsqlAuthProxy:
  enabled: true
  connectionName: "hpe-labs-ai:us-central1:det-pach-seldon-db"
  serviceAccount: "det-pach-seldon-sa@hpe-labs-ai.iam.gserviceaccount.com"
  resources:
    requests:
      memory: "500Mi"
      cpu:    "250m"

global:
  postgresql:
    # User "pachyderm" and database "pachyderm" must be created in advance
    # Database must use Cloud DNS for the name (otherwise looks for a service)
    # Password for user "pachyderm"
    #postgresqlPassword: "postgres.123"
    #postgresqlHost: "pachyderm-db.determined"
    # The postgresql database host to connect to. Defaults to postgres service in subchart
    postgresqlHost: "cloudsql-auth-proxy.default.svc.cluster.local."
    #postgresqlHost: "34.135.2.69"
    # The postgresql database port to connect to. Defaults to postgres server in subchart
    postgresqlPort: "5432"
    postgresqlSSL: "disable"
    postgresqlUsername: "postgres"
    postgresqlPassword: "Pachyderm1!"
    
pachd:
  enabled: true
  storage:
    google:
      bucket: "det-pach-seldon-checkpoint"
  serviceAccount:
    additionalAnnotations:
      iam.gke.io/gcp-service-account: "det-pach-seldon-sa@hpe-labs-ai.iam.gserviceaccount.com"
    name:   "pachyderm"
  worker:
    serviceAccount:
      additionalAnnotations:
        iam.gke.io/gcp-service-account: "det-pach-seldon-sa@hpe-labs-ai.iam.gserviceaccount.com"
    name:   "pachyderm-worker"

postgresql:
  enabled: false
